# Generated by Django 4.2.9 on 2024-01-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewset", "0002_stu_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stu",
            options={"verbose_name": "Stu"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher"},
        ),
    ]
