# Generated by Django 4.2.9 on 2024-01-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewset", "0003_alter_stu_options_alter_teacher_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user_ptr",
        ),
        migrations.DeleteModel(
            name="Stu",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
